'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class frmDadosDosPeritos

    '''<summary>
    '''FrmAutoriza control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FrmAutoriza As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''DGTECTextBox9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DGTECTextBox9 As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''DGTECTextBox13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DGTECTextBox13 As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''DGTECTextBox10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DGTECTextBox10 As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''DGTECTextBox14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DGTECTextBox14 As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''DGTECTextBox11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DGTECTextBox11 As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''DGTECTextBox15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DGTECTextBox15 As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''DGTECTextBox12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DGTECTextBox12 As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''DGTECTextBox16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DGTECTextBox16 As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''DGTECTextBox6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DGTECTextBox6 As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''DGTECTextBox7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DGTECTextBox7 As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''DGTECTextBox8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DGTECTextBox8 As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''DGTECTextBox17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DGTECTextBox17 As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''DGTECTextBox3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DGTECTextBox3 As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''DGTECTextBox4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DGTECTextBox4 As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''DGTECTextBox5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DGTECTextBox5 As Global.ClienteWebPadrao.DGTECTextBox
End Class
