'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmConsProcPer

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''txtNum_Processo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNum_Processo As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''txtNum_CNJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNum_CNJ As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''GrdProcPerito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrdProcPerito As Global.ClienteWebPadrao.DGTECGridView

    '''<summary>
    '''CboProfissao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CboProfissao As Global.ClienteWebPadrao.DGTECDropDownList

    '''<summary>
    '''CboEspecialidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CboEspecialidade As Global.ClienteWebPadrao.DGTECDropDownList

    '''<summary>
    '''CboPerito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CboPerito As Global.ClienteWebPadrao.DGTECDropDownList

    '''<summary>
    '''LblAnotacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblAnotacao As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''txtAnotacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnotacao As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''BtnNovo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnNovo As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''lblData_Nomeacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblData_Nomeacao As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''lblEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmail As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''lblEmail1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmail1 As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''chkLaudoLiberado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkLaudoLiberado As Global.ClienteWebPadrao.DGTECCheckBox

    '''<summary>
    '''lblData_Liberacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblData_Liberacao As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''lblData_Cadastramento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblData_Cadastramento As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''txtQteAceitos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQteAceitos As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''txtQtePendentes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtePendentes As Global.ClienteWebPadrao.DGTECTextBox
End Class
