'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmDeclaracaoPsicRes

    '''<summary>
    '''FrmAutoriza control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FrmAutoriza As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''DGTECTextBox6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DGTECTextBox6 As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''DGTECTextBox2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DGTECTextBox2 As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''DGTECTextBox3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DGTECTextBox3 As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''DGTECTextBox4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DGTECTextBox4 As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''DGTECTextBox5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DGTECTextBox5 As Global.ClienteWebPadrao.DGTECTextBox
End Class
