'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmPeritoDCP

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lblOrgaoUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrgaoUsuario As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''txtNum_Processo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNum_Processo As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''txtNum_CNJ1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNum_CNJ1 As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''txtNum_CNJ2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNum_CNJ2 As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''txtNum_CNJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNum_CNJ As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''txtID_Nomeacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtID_Nomeacao As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''BtnVerCNJPendS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnVerCNJPendS As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''BtnVerCNJPend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnVerCNJPend As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''LblNumProcExemplo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblNumProcExemplo As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''txtNumProcExemplo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumProcExemplo As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''pnlPeritos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPeritos As Global.ClienteWebPadrao.DGTECPanel

    '''<summary>
    '''GrdProcPerito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrdProcPerito As Global.ClienteWebPadrao.DGTECGridView

    '''<summary>
    '''pnlInfNomeacaoPerito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInfNomeacaoPerito As Global.ClienteWebPadrao.DGTECPanel

    '''<summary>
    '''CboProfissao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CboProfissao As Global.ClienteWebPadrao.DGTECDropDownList

    '''<summary>
    '''CboEspecialidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CboEspecialidade As Global.ClienteWebPadrao.DGTECDropDownList

    '''<summary>
    '''txtNome_Perito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNome_Perito As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''txtID_PF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtID_PF As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''BtnPerito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnPerito As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''BtnCurriculum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCurriculum As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''BtnVerFoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnVerFoto As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''BtnNovoPer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnNovoPer As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''lblData_Cadastramento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblData_Cadastramento As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''txtQtePendentes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtePendentes As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''txtQteAceitos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQteAceitos As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''txtQteRecusadas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQteRecusadas As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''LblAnotacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblAnotacao As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''txtAnotacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnotacao As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''lblEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmail As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''lblEmail1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmail1 As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''pnlInformacoesNomeacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInformacoesNomeacao As Global.ClienteWebPadrao.DGTECPanel

    '''<summary>
    '''lblData_Nomeacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblData_Nomeacao As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''lblAceitacao_Tacita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAceitacao_Tacita As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''lblData_Aceitacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblData_Aceitacao As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''lblData_Seg_Aceitacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblData_Seg_Aceitacao As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''lblAceitacao_TacitaPos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAceitacao_TacitaPos As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''lblData_Negacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblData_Negacao As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''lblMotivo_Recusa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMotivo_Recusa As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''txtMotivo_Recusa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMotivo_Recusa As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''lblJG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJG As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''RdbJustGrat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RdbJustGrat As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txtPrazo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrazo As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''txtHonPer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHonPer As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''txtHonJuiz control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHonJuiz As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''lblData_Novo_Hon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblData_Novo_Hon As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''ChkPerInter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkPerInter As Global.ClienteWebPadrao.DGTECCheckBox

    '''<summary>
    '''BtnInicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnInicio As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''lblData_Inicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblData_Inicio As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''PanelPagtoPerito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelPagtoPerito As Global.ClienteWebPadrao.DGTECPanel

    '''<summary>
    '''tbAceiteLaudo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAceiteLaudo As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''RdInterdicao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RdInterdicao As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''chkLaudoLiberado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkLaudoLiberado As Global.ClienteWebPadrao.DGTECCheckBox

    '''<summary>
    '''lblData_Liberacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblData_Liberacao As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''chkLaudoCancelado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkLaudoCancelado As Global.ClienteWebPadrao.DGTECCheckBox

    '''<summary>
    '''lblData_Cancelamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblData_Cancelamento As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''BtnGravar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnGravar As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''BtnNovo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnNovo As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''BtnEmailNomeacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnEmailNomeacao As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''BtnAnotacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAnotacao As Global.ClienteWebPadrao.DGTECButton
End Class
