'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmConsultaPagamentosRealizados

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''up1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents up1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblTipoPessoa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTipoPessoa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlTipoPessoa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoPessoa As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCodPerito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodPerito As Global.ClienteWebPadrao.DGTECHiddenField

    '''<summary>
    '''lblCPF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCPF As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCPF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCPF As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''lblCNPJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCNPJ As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCNPJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCNPJ As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnImprimir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnImprimir As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''BtnLimpar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnLimpar As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''BtnSair control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSair As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''lblNome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNome As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNome As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''lblNomeParecido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomeParecido As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlNomeSemelhante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNomeSemelhante As Global.ClienteWebPadrao.DGTECDropDownList

    '''<summary>
    '''linhaPessoaJuridica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linhaPessoaJuridica As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblNomePJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomePJ As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNomeFantasia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNomeFantasia As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''lblProfissao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProfissao As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlProfissao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProfissao As Global.ClienteWebPadrao.DGTECDropDownList

    '''<summary>
    '''lblEspecialidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEspecialidade As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlEspecialidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEspecialidade As Global.ClienteWebPadrao.DGTECDropDownList

    '''<summary>
    '''lblOficio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOficio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOficio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOficio As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''lblNumeroProcesso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumeroProcesso As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNumeroProcesso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumeroProcesso As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''ddlProcessosRelacionados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProcessosRelacionados As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblRelacaoPagamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRelacaoPagamento As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlRelacaoPagamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRelacaoPagamento As Global.ClienteWebPadrao.DGTECDropDownList

    '''<summary>
    '''lblProcessoPagamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProcessoPagamento As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtProcessoPagamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProcessoPagamento As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''lblDataProtocoloInicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataProtocoloInicial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDataProtocoloInicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataProtocoloInicial As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''lblDataProtocoloFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataProtocoloFinal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDataProtocoloFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataProtocoloFinal As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''lblDataPagamentoInicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataPagamentoInicial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDataPagamentoInicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataPagamentoInicial As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''lblDataPagamentoFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataPagamentoFinal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDataPagamentoFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataPagamentoFinal As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''grdAjudaCusto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdAjudaCusto As Global.ClienteWebPadrao.DGTECGridView

    '''<summary>
    '''lblQntdPags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQntdPags As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''uppC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uppC As Global.System.Web.UI.UpdateProgress
End Class
