'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmRelacaoPagamento

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''up1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents up1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblNomeRelacaoPagamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomeRelacaoPagamento As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNomeRelacaoPagamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNomeRelacaoPagamento As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''lblRelacaoPgtoSemelhantes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRelacaoPgtoSemelhantes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlRelacaoPgtoSemelhantes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRelacaoPgtoSemelhantes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblRelacaoDefinitiva control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRelacaoDefinitiva As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkRelacaoDefinitiva control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRelacaoDefinitiva As Global.ClienteWebPadrao.DGTECCheckBox

    '''<summary>
    '''txtIdRelacaoPagamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIdRelacaoPagamento As Global.ClienteWebPadrao.DGTECHiddenField

    '''<summary>
    '''BtnGravar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnGravar As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''btnImprimir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnImprimir As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''BtnLimpar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnLimpar As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''BtnSair control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSair As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''pnlListaAjudaRelacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlListaAjudaRelacao As Global.ClienteWebPadrao.DGTECPanel

    '''<summary>
    '''grdAjudaCustoRelacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdAjudaCustoRelacao As Global.ClienteWebPadrao.DGTECGridView

    '''<summary>
    '''btnNovaAjudaCusto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNovaAjudaCusto As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlPeritoAjudaCusto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPeritoAjudaCusto As Global.ClienteWebPadrao.DGTECPanel

    '''<summary>
    '''txtNomePerito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNomePerito As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''ddlNomeSemelhante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNomeSemelhante As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnNovoPerito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNovoPerito As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''txtCpfCnpj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCpfCnpj As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''txtCodPerito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodPerito As Global.ClienteWebPadrao.DGTECHiddenField

    '''<summary>
    '''ddlNumeroConselho control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNumeroConselho As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlSigla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSigla As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlUF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlUF As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlProfissao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProfissao As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlEspecialidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEspecialidade As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtNumeroOficio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumeroOficio As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''txtDataRecebimentoOficio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataRecebimentoOficio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnInserirAjudaCusto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnInserirAjudaCusto As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''txtNumeroProcesso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumeroProcesso As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''ddlProcessosRelacionados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProcessosRelacionados As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtValor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValor As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''txtProcessoPagamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProcessoPagamento As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''txtDataProtocolo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataProtocolo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDataPagamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataPagamento As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIdAjudaCusto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIdAjudaCusto As Global.ClienteWebPadrao.DGTECHiddenField

    '''<summary>
    '''txtSeqAjudaCusto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSeqAjudaCusto As Global.ClienteWebPadrao.DGTECHiddenField

    '''<summary>
    '''txtObs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObs As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''grdAjudaCustoPerito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdAjudaCustoPerito As Global.ClienteWebPadrao.DGTECGridView

    '''<summary>
    '''uppC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uppC As Global.System.Web.UI.UpdateProgress
End Class
