'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LayoutPrincipal

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''lblNomeUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomeUsuario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAmbiente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAmbiente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''L1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DIPEJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DIPEJ As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Li2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Auxiliares control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Auxiliares As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Li3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Nomeacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Nomeacao As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Perito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Perito As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Li1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Li1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Tela control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tela As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
