'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmDetalhesPerito

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''pnlPagina control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPagina As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblTituloNomePerito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloNomePerito As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNomePerito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomePerito As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTituloCpfCnpj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloCpfCnpj As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCpfCnpj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCpfCnpj As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTituloStatusPerito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloStatusPerito As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStatusPerito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatusPerito As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tblAnotacoes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblAnotacoes As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''imgFotoPerito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgFotoPerito As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''tblProfissoes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblProfissoes As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Image2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblTituloEmailPrincipal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloEmailPrincipal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hlEmailPrincipal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlEmailPrincipal As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblTituloEmailAnternativo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloEmailAnternativo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hlEmailAlternativo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlEmailAlternativo As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''grdTelefone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdTelefone As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblTituloLogrResidencial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloLogrResidencial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLogrResidencial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLogrResidencial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTituloNumeroResidencial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloNumeroResidencial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNumeroResidencial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumeroResidencial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTituloComplementoResidencial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloComplementoResidencial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblComplementoResidencial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComplementoResidencial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTituloBairroResidencial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloBairroResidencial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBairroResidencial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBairroResidencial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTituloCEPResidencial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloCEPResidencial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCEPResidencial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCEPResidencial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTituloCidadeResidencial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloCidadeResidencial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCidadeResidencial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCidadeResidencial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTituloUFResidencial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloUFResidencial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUFResidencial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUFResidencial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTituloLogrComercial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloLogrComercial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLogrComercial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLogrComercial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTituloNumeroComercial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloNumeroComercial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNumeroComercial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumeroComercial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTituloComplementoComercial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloComplementoComercial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblComplementoComercial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComplementoComercial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTituloBairroComercial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloBairroComercial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBairroComercial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBairroComercial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTituloCEPComercial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloCEPComercial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCEPComercial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCEPComercial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTituloCidadeComercial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloCidadeComercial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCidadeComercial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCidadeComercial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTituloUFComercial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloUFComercial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUFComercial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUFComercial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTituloPeritoJuizo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloPeritoJuizo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPeritoJuizo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPeritoJuizo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTituloDataCadastro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloDataCadastro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDataCadastro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataCadastro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTituloDataMigração control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloDataMigração As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDataMigração control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataMigração As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tblNursComarcas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblNursComarcas As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''grdDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdDoc As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
End Class
