'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmPreCadastroPeritoExt

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''upPrincipal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upPrincipal As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtCPF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCPF As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''mskdTxtCPF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mskdTxtCPF As Global.AjaxControlToolkit.MaskedEditExtender

    '''<summary>
    '''txtNome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNome As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''txtDt_Nasc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDt_Nasc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''mskDtNascimento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mskDtNascimento As Global.AjaxControlToolkit.MaskedEditExtender

    '''<summary>
    '''BtnGravar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnGravar As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''BtnLimpar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnLimpar As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''upTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upTab As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''TabContainer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabContainer1 As Global.AjaxControlToolkit.TabContainer

    '''<summary>
    '''tbpEndRes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpEndRes As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''txtCEP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCEP As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''mskTxtCepResidencial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mskTxtCepResidencial As Global.AjaxControlToolkit.MaskedEditExtender

    '''<summary>
    '''CboUF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CboUF As Global.ClienteWebPadrao.DGTECDropDownList

    '''<summary>
    '''CboCidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CboCidade As Global.ClienteWebPadrao.DGTECDropDownList

    '''<summary>
    '''CboBairro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CboBairro As Global.ClienteWebPadrao.DGTECDropDownList

    '''<summary>
    '''CboTip_Logr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CboTip_Logr As Global.ClienteWebPadrao.DGTECDropDownList

    '''<summary>
    '''txtNome_Logr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNome_Logr As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''txtNum_Logr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNum_Logr As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''txtCompl_Logr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompl_Logr As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''tbpEndCom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpEndCom As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''txtCEP1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCEP1 As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''mskTxtCepComercial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mskTxtCepComercial As Global.AjaxControlToolkit.MaskedEditExtender

    '''<summary>
    '''CboUF1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CboUF1 As Global.ClienteWebPadrao.DGTECDropDownList

    '''<summary>
    '''CboCidade1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CboCidade1 As Global.ClienteWebPadrao.DGTECDropDownList

    '''<summary>
    '''CboBairro1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CboBairro1 As Global.ClienteWebPadrao.DGTECDropDownList

    '''<summary>
    '''CboTip_Logr1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CboTip_Logr1 As Global.ClienteWebPadrao.DGTECDropDownList

    '''<summary>
    '''txtNome_Logr1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNome_Logr1 As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''txtNum_Logr1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNum_Logr1 As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''txtCompl_Logr1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompl_Logr1 As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''tbpTelefone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpTelefone As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''GrdTel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrdTel As Global.ClienteWebPadrao.DGTECGridView

    '''<summary>
    '''cboCodTipTel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCodTipTel As Global.ClienteWebPadrao.DGTECDropDownList

    '''<summary>
    '''txtDDD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDDD As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''mskTxtDDD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mskTxtDDD As Global.AjaxControlToolkit.MaskedEditExtender

    '''<summary>
    '''txtTel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTel As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''msktxtTel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msktxtTel As Global.AjaxControlToolkit.MaskedEditExtender

    '''<summary>
    '''lblRamal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRamal As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''mskTxtRamal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mskTxtRamal As Global.AjaxControlToolkit.MaskedEditExtender

    '''<summary>
    '''TxtRamal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtRamal As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''btnGravarTel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGravarTel As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''TbpProfissao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TbpProfissao As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''GrdProfissao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrdProfissao As Global.ClienteWebPadrao.DGTECGridView

    '''<summary>
    '''CboProfissao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CboProfissao As Global.ClienteWebPadrao.DGTECDropDownList

    '''<summary>
    '''CboEspecialidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CboEspecialidade As Global.ClienteWebPadrao.DGTECDropDownList

    '''<summary>
    '''CboOrgao_Per control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CboOrgao_Per As Global.ClienteWebPadrao.DGTECDropDownList

    '''<summary>
    '''lblSiglaProf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSiglaProf As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''txtNum_Reg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNum_Reg As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''drpUFProf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpUFProf As Global.ClienteWebPadrao.DGTECDropDownList

    '''<summary>
    '''btnAtualizarProf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAtualizarProf As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''tbpInfAdicionais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpInfAdicionais As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''BtnNur1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnNur1 As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''BtnNur2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnNur2 As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''BtnNur3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnNur3 As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''BtnNur4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnNur4 As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''BtnNur5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnNur5 As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''BtnNur6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnNur6 As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''BtnNur7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnNur7 As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''BtnNur8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnNur8 As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''BtnNur9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnNur9 As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''BtnNur10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnNur10 As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''BtnNur11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnNur11 As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''BtnNur12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnNur12 As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''BtnNur13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnNur13 As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''btnNurMarcarTodos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNurMarcarTodos As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''btnNurDesmarcarTodos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNurDesmarcarTodos As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''ValidarEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidarEmail As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''ValidarEmail1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidarEmail1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmail As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''txtEmail1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmail1 As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''uppTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uppTab As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''uppPrincipal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uppPrincipal As Global.System.Web.UI.UpdateProgress
End Class
