'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmPeritoDCP

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''txtNum_Processo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNum_Processo As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''txtNum_CNJ1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNum_CNJ1 As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''txtNum_CNJ2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNum_CNJ2 As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''txtNum_CNJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNum_CNJ As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''pnlPeritos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPeritos As Global.ClienteWebPadrao.DGTECPanel

    '''<summary>
    '''GrdProcPerito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrdProcPerito As Global.ClienteWebPadrao.DGTECGridView

    '''<summary>
    '''pnlInfNomeacaoPerito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInfNomeacaoPerito As Global.ClienteWebPadrao.DGTECPanel

    '''<summary>
    '''CboProfissao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CboProfissao As Global.ClienteWebPadrao.DGTECDropDownList

    '''<summary>
    '''CboEspecialidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CboEspecialidade As Global.ClienteWebPadrao.DGTECDropDownList

    '''<summary>
    '''txtNome_Perito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNome_Perito As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''txtID_PF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtID_PF As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''BtnPerito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnPerito As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''BtnCurriculum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCurriculum As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''BtnVerFoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnVerFoto As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''LblAnotacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblAnotacao As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''txtAnotacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnotacao As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''lblData_Nomeacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblData_Nomeacao As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''ChkJustGrat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkJustGrat As Global.ClienteWebPadrao.DGTECCheckBox

    '''<summary>
    '''tbPisq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPisq As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''ChkPsiqLocal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkPsiqLocal As Global.ClienteWebPadrao.DGTECCheckBox

    '''<summary>
    '''chkPsiqAudiencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPsiqAudiencia As Global.ClienteWebPadrao.DGTECCheckBox

    '''<summary>
    '''lblData_Aceitacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblData_Aceitacao As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''lblData_Negacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblData_Negacao As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''lblEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmail As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''lblEmail1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmail1 As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''txtPrazo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrazo As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''lblData_Cadastramento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblData_Cadastramento As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''txtQteAceitos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQteAceitos As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''txtQtePendentes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtePendentes As Global.ClienteWebPadrao.DGTECTextBox

    '''<summary>
    '''pnlPagamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPagamento As Global.ClienteWebPadrao.DGTECPanel

    '''<summary>
    '''tbAceiteLaudo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAceiteLaudo As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''chkLaudoLiberado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkLaudoLiberado As Global.ClienteWebPadrao.DGTECCheckBox

    '''<summary>
    '''lblData_Liberacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblData_Liberacao As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''ChkCancelaPgto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkCancelaPgto As Global.ClienteWebPadrao.DGTECCheckBox

    '''<summary>
    '''lblData_Cancelamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblData_Cancelamento As Global.ClienteWebPadrao.DGTECLabel

    '''<summary>
    '''BtnGravar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnGravar As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''BtnNovo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnNovo As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''BtnEmailNomeacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnEmailNomeacao As Global.ClienteWebPadrao.DGTECButton

    '''<summary>
    '''BtnAnotacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAnotacao As Global.ClienteWebPadrao.DGTECButton
End Class
